statements:
  - "Dramatic pause."
insults:
  - "That was so terrible, I think you gave me cancer! I don't care how popular you are, you will never work on my show!"
intros:
  - "I am but a simple actor, but... I think.."
greetings:
  - "I was all of history's great acting robots: Acting Unit 0.8, Thespo-mat, David Duchovny!"
  - "Noooooooooo"
  - "I'm a washed up ham"
confused:
  - "I'm unfamiliar with the... type of thing I'm seeing."